export interface RJStation {
  id: string;
  name: string;
  frequency: string;
  genre: string;
  city: string;
  url: string;
  favicon?: string;
}

// Emissoras do Rio de Janeiro (curadoria deduplicada a partir da Radio Browser API).
export const RJ_STATIONS: RJStation[] = [
  {
    id: "102-fm-itaperuna",
    name: "102 FM Itaperuna",
    frequency: "",
    genre: "",
    city: "Itaperuna",
    url: "https://radio.saopaulo01.com.br:10948/stream",
  },
  {
    id: "antena-1",
    name: "Antena 1",
    frequency: "103.7 FM",
    genre: "Adult Contemporary, MPB",
    city: "Rio de Janeiro",
    url: "http://a1rj.streams.com.br:7801/stream",
    favicon:
      "https://www.antena1rio.com.br/wp-content/uploads/2024/01/logo-antena-1.png",
  },
  {
    id: "cbn-rio",
    name: "CBN Rio",
    frequency: "92.5 FM",
    genre: "NotÃ­cias",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/CBN_RJ_ADP.m3u8",
  },
  {
    id: "clube-da-black-music",
    name: "Clube da Black Music",
    frequency: "",
    genre: "Black Music",
    city: "Rio de Janeiro",
    url: "https://servidor37-2.brlogic.com:8066/live?source=website",
    favicon:
      "https://public-rf-upload.minhawebradio.net/23914/cover/3c5997fe2d907398b689858e9686ac0d.png",
  },
  {
    id: "conselheiro-87-7",
    name: "Conselheiro FM",
    frequency: "87.7 FM",
    genre: "ComunitÃ¡ria, EclÃ©tica",
    city: "Rio de Janeiro",
    url: "http://stm1.streamproarte.com.br:7204/stream",
  },
  {
    id: "eldopop",
    name: "EldoPop FM",
    frequency: "",
    genre: "Hard Rock, Progressive Rock",
    city: "Rio de Janeiro",
    url: "http://stm10.srvstm.com:34794/stream",
    favicon: "http://eldopopfm.com/admin/assets/img/favicon.jpg",
  },
  {
    id: "elektra-radio",
    name: "Elektra Radio",
    frequency: "",
    genre: "Electro, Synthpop, Indie Rock",
    city: "Rio de Janeiro",
    url: "https://cast3.hoost.com.br:8952/stream",
    favicon:
      "https://www.elektraradio.com/files/2026/01/logo_elektra_raio_03_mini-1.png",
  },
  {
    id: "fm-o-dia",
    name: "FM O Dia",
    frequency: "100.5 FM",
    genre: "Samba & Pagode",
    city: "Rio de Janeiro",
    url: "http://streaming.livespanel.com:20000/live",
  },
  {
    id: "fm-o-dia-macae",
    name: "FM O Dia MacaÃ©",
    frequency: "99.7 FM",
    genre: "Samba & Pagode",
    city: "MacaÃ©",
    url: "https://wz7.servidoresbrasil.com:8274/stream",
    favicon:
      "https://img.radios.com.br/radio/lg/radio229211_1706128532.jpeg",
  },
  {
    id: "hitmix-brasil",
    name: "Hitmix Brasil",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "https://radio.stmsrv.com:8464/stream",
  },
  {
    id: "jb-fm",
    name: "JB FM",
    frequency: "99.9 FM",
    genre: "MÃºsica, Flashback, MPB",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/JBFMAAC.aac",
  },
  {
    id: "manchete-fm",
    name: "Manchete FM",
    frequency: "104.9 FM",
    genre: "MÃºsica",
    city: "Rio de Janeiro",
    url: "https://8410.brasilstream.com.br/stream?origem=site",
    favicon:
      "https://mancheterio.com.br/wp-content/uploads/2023/04/icone-manchete-96-1-150x150.png",
  },
  {
    id: "melodia-fm",
    name: "RÃ¡dio Melodia",
    frequency: "97.5 FM",
    genre: "Gospel",
    city: "Rio de Janeiro",
    url: "https://server01.ouvir.radio.br:8033/stream",
    favicon: "https://melodia.com.br/favicon.ico",
  },
  {
    id: "mix-rio",
    name: "Mix Rio",
    frequency: "102.1 FM",
    genre: "Top 40, Pop",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MIXRIOAAC.aac",
  },
  {
    id: "nova-brasil",
    name: "Nova Brasil FM",
    frequency: "89.5 FM",
    genre: "MPB, MÃºsica brasileira",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/NOVABRASIL_RIOAAC.aac",
  },
  {
    id: "positividade-fm",
    name: "Positividade FM",
    frequency: "95.1 FM",
    genre: "Pop, MÃºsica",
    city: "Rio de Janeiro",
    url: "https://27373.live.streamtheworld.com/POSITIVIDADE_FMAAC.aac",
    favicon:
      "https://positividade.fm/wp-content/uploads/2022/04/favicon-32x32-1.png",
  },
  {
    id: "progsky",
    name: "Progsky",
    frequency: "",
    genre: "Progressive Rock",
    city: "Rio de Janeiro",
    url: "https://cc4.streammaximum.com:20017/stream",
    favicon:
      "https://www.progsky.com/wp-content/uploads/2024/08/LOGOBALANCE.png",
  },
  {
    id: "bandnews-rio",
    name: "BandNews FM Rio",
    frequency: "90.3 FM",
    genre: "NotÃ­cias",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/BANDNEWSFM_RJAAC.aac",
  },
  {
    id: "radio-catedral",
    name: "RÃ¡dio Catedral",
    frequency: "106.7 FM",
    genre: "CatÃ³lica",
    city: "Rio de Janeiro",
    url: "https://hts04.brascast.com:13728/live",
    favicon:
      "https://radiocatedral.com.br/wp-content/uploads/2019/07/logo-catedral-oficial-e1562107838784.jpg",
  },
  {
    id: "radio-charme",
    name: "RÃ¡dio Charme",
    frequency: "",
    genre: "Hip-Hop, R&B, Soul",
    city: "Rio de Janeiro",
    url: "https://stm6.xcast.com.br:7988/stream",
    favicon: "https://i.imgur.com/cGgYqri.jpeg",
  },
  {
    id: "radio-cidade",
    name: "RÃ¡dio Cidade",
    frequency: "102.9 FM",
    genre: "Pop & Rock",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOCIDADEAAC.aac",
    favicon: "https://radiocidade.fm/favicon.ico",
  },
  {
    id: "radio-coroados",
    name: "RÃ¡dio Coroados AM",
    frequency: "AM 1310",
    genre: "",
    city: "Rio de Janeiro",
    url: "https://s41.maxcast.com.br:8176/live",
  },
  {
    id: "radio-costazul",
    name: "RÃ¡dio Costazul FM",
    frequency: "",
    genre: "",
    city: "Angra dos Reis",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/COSTAZULFMAAC.aac",
    favicon:
      "https://costazul.fm/wp-content/uploads/2021/04/logotipo-costaazul.png",
  },
  {
    id: "radio-elohim",
    name: "RÃ¡dio Elohim",
    frequency: "",
    genre: "CristÃ£",
    city: "Rio de Janeiro",
    url: "https://servidor34-5.brlogic.com:8190/live",
  },
  {
    id: "radio-escola-de-radio",
    name: "RÃ¡dio Escola de RÃ¡dio",
    frequency: "",
    genre: "MPB, Pop, Rock",
    city: "Rio de Janeiro",
    url: "https://radio.escoladeradio.com.br/listen/radio_er/radio.mp3",
    favicon: "https://www.escoladeradio.com.br/radio-icon-512.png",
  },
  {
    id: "radio-estilo-leblon",
    name: "RÃ¡dio Estilo Leblon",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "http://198.58.98.83:8193/stream",
  },
  {
    id: "radio-furacao-2000",
    name: "RÃ¡dio FuracÃ£o 2000",
    frequency: "",
    genre: "Pop, Dance",
    city: "Rio de Janeiro",
    url: "https://servidor24-1.brlogic.com:7516/live?source=website",
    favicon:
      "https://public-rf-upload.minhawebradio.net/111279/mobileicon/d5b82a5ec287583c0d89eaa8726c323fx192.png",
  },
  {
    id: "radio-globo",
    name: "RÃ¡dio Globo",
    frequency: "98.1 FM",
    genre: "Jornalismo & Esportes",
    city: "Rio de Janeiro",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO_RJAAC.aac",
    favicon:
      "https://img.radios.com.br/radio/lg/radio8817_1676300226.png",
  },
  {
    id: "radio-graviola",
    name: "RÃ¡dio Graviola",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "http://servidor30.brlogic.com:8262/live",
    favicon:
      "https://radiograviola.com/wp-content/themes/radio-graviola/dist/assets/img/favicon/apple-touch-icon.png",
  },
  {
    id: "radio-lam",
    name: "RÃ¡dio LAM",
    frequency: "",
    genre: "Rock, Blues",
    city: "Rio de Janeiro",
    url: "https://stream1.svrdedicado.org/8028/stream",
    favicon:
      "https://static.wixstatic.com/media/a50a7a_81465ac4da92440e8e9dbca4534a3a02~mv2.png",
  },
  {
    id: "radio-maravilha",
    name: "RÃ¡dio Maravilha FM",
    frequency: "",
    genre: "",
    city: "PetrÃ³polis",
    url: "https://stm39.srvstm.com:8758/stream",
  },
  {
    id: "radio-mec-am",
    name: "RÃ¡dio MEC AM",
    frequency: "",
    genre: "Jazz, MPB, Instrumental",
    city: "Rio de Janeiro",
    url: "https://radiomec-stream.ebc.com.br/ebc/radiomec/playlist.m3u8",
    favicon:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.seeklogo.com%2Flogo-png%2F49%2F1%2Fradio-mec-logo-png_seeklogo-494149.png&f=1&nofb=1&ipt=27ab00eb7c162df6795eb22aa64d4ce46646ba94477f562bb2907be4ba990d63",
  },
  {
    id: "radio-mec-fm",
    name: "RÃ¡dio MEC FM",
    frequency: "",
    genre: "MÃºsica clÃ¡ssica, MPB",
    city: "Rio de Janeiro",
    url: "https://radiomecfm-stream.ebc.com.br/ebc/radiomecfm/MEC_FM-mp4a_277200_eng=20000.m3u8",
  },
  {
    id: "radio-nacional-rio",
    name: "RÃ¡dio Nacional do Rio",
    frequency: "",
    genre: "NotÃ­cias, Esportes, MPB",
    city: "Rio de Janeiro",
    url: "https://radionacionalrio-stream.ebc.com.br/ebc/radionacionalriodejaneiro/playlist.m3u8",
    favicon:
      "https://yt3.googleusercontent.com/9M9Ulf03D2Ms6haBGOclxqov778KbJdPgh7HlLjMrJOlvaQ4wf_3kqFb6armS5M1kn4ZvLdJmeE=s900-c-k-c0x00ffffff-no-rj",
  },
  {
    id: "radio-rede-3-16",
    name: "RÃ¡dio Rede 3.16",
    frequency: "",
    genre: "Gospel",
    city: "Rio de Janeiro",
    url: "https://servidor21.brlogic.com:7976/live",
    favicon:
      "https://www.cxradio.com.br/img/Radio/Logo/70513e19e133ed1f3c2195559f7b8807.png",
  },
  {
    id: "radio-roquette-pinto",
    name: "RÃ¡dio Roquette Pinto",
    frequency: "82.9 FM",
    genre: "EclÃ©tica",
    city: "Rio de Janeiro",
    url: "https://radio.saopaulo01.com.br/8300/stream/",
    favicon:
      "https://radioroquettepinto.rj.gov.br/sites/default/themes/rjgov/favicon.ico",
  },
  {
    id: "radio-tabira",
    name: "RÃ¡dio Tabira",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "https://server27.srvsh.com.br:8590/stream",
    favicon: "https://i.ibb.co/fYPkym6J/Radido-Tabira-faveicon.jpg",
  },
  {
    id: "radio-teresopolis",
    name: "RÃ¡dio TeresÃ³polis",
    frequency: "",
    genre: "NotÃ­cias, Talk",
    city: "TeresÃ³polis",
    url: "http://cast3.hoost.com.br:8096/stream",
  },
  {
    id: "radio-ufrj",
    name: "RÃ¡dio UFRJ",
    frequency: "99.9 FM",
    genre: "MÃºsica brasileira",
    city: "Rio de Janeiro",
    url: "https://servidor21.brlogic.com:7712/live",
    favicon: "https://www.radio.ufrj.br/images/favicon.png",
  },
  {
    id: "radio-vibe-ploc",
    name: "RÃ¡dio Vibe Ploc",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "https://s43.maxcast.com.br:9082/live",
  },
  {
    id: "radio-web-clube-sertanejo",
    name: "RÃ¡dio Web Clube Sertanejo",
    frequency: "",
    genre: "Sertanejo",
    city: "Itaperuna",
    url: "https://s42.maxcast.com.br:8180/live",
    favicon:
      "https://radiowebclubesertanejo.com/imagens/47485b4984a407f96e703cfc50b183c0.png",
  },
  {
    id: "rio-sul-radio",
    name: "Rio Sul Radio",
    frequency: "",
    genre: "Pop Rock, Adult Contemporary",
    city: "Rio de Janeiro",
    url: "https://stream.riosulradio.com/",
    favicon: "https://riosulradio.com/assets/img/logo.png",
  },
  {
    id: "serra-verde-fm",
    name: "Serra Verde FM",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "http://40.160.24.87:10650/stream",
  },
  {
    id: "so-cacarecos",
    name: "SÃ³ Cacarecos",
    frequency: "",
    genre: "Classic Rock, Progressive Rock",
    city: "Rio de Janeiro",
    url: "http://sokakarecos.ddns.net:9030/rock128",
  },
  {
    id: "sucesso-fm",
    name: "Sucesso FM",
    frequency: "88.3 FM",
    genre: "Pop, Pagode, Sertanejo",
    city: "Nova Friburgo",
    url: "https://servidor36.brlogic.com:8300/live",
    favicon:
      "https://public-rf-upload.minhawebradio.net/17549/program/7d841a5fa803032a7e8656166559739f.jpg",
  },
  {
    id: "super-radio-tupi",
    name: "Super RÃ¡dio Tupi",
    frequency: "96.5 FM",
    genre: "Popular, Variedades",
    city: "Rio de Janeiro",
    url: "https://8923.brasilstream.com.br/stream",
  },
  {
    id: "webradio-rama",
    name: "Web RÃ¡dio Rama",
    frequency: "",
    genre: "CristÃ£",
    city: "Rio de Janeiro",
    url: "https://servidor32-5.brlogic.com:8464/live?source=website",
    favicon:
      "https://public-rf-upload.minhawebradio.net/9162/mobileicon/a75c9d7bfcacdbf6d85c5d42bb741b6bx192.png",
  },
  {
    id: "bailao-mysterious",
    name: "BailÃ£o Mysterious Radio",
    frequency: "",
    genre: "",
    city: "Rio de Janeiro",
    url: "https://stream.zeno.fm/5vxixvrpqentv",
  },
];
